name: CD deploy new feature enviroment production
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
        
      - name: Install ng
        run: npm install -g @angular/cli@latest
        
      - name: Build App
        run: ng build
        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          
      - name: Enviando para s3
        run: aws s3 sync ./dist/ProEventos-App s3://test-deploy-angular-github
